# explicit wildcard expansion suppresses errors when no files are found
# include $(wildcard *.deps)

# %.png: %.scad
# 	openscad -m make -o $@ -d $@.deps $<

all:
	$(MAKE) -C foundation all

clean:
	$(MAKE) -C foundation clean
