name: Publish Documentation

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ggabbiani/ofl:ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /import

      - name: Generate Documentation
        shell: bash
        run: |
          # Qui eseguiamo quello che il tuo container fa all'avvio.
          # Se il container ha un ENTRYPOINT che genera i file,
          # GitHub Actions lo ignora, quindi lanciamo il comando esplicito.
          # Assumendo che il comando sia 'make' o lo script di orthodocs:
          # orthodocs --input ./src --output ./docs/api-docs
          source .venv/bin/activate
          xvfb-run -d make SHELL="$(which bash)" -s docs/all
          # Aggiungi qui eventuali altri comandi necessari per i Markdown non-API

      - name: Deploy with Mike
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///' | cut -d. -f1,2)
            mike deploy --push --update-aliases $VERSION latest
          else
            mike deploy --push main
          fi