# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ODOX_URL:   https://github.com/ggabbiani/orthodocs/releases/download/v1.2.1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  fedora:
    name: Fedora 39
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ofl:fedora
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Project checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches
          # and tags (default 1).
          fetch-depth: '0'

      # System update and pre-requisite install
      - name: System setup
        run: |
          sudo apt update
          sudo apt upgrade -y
          python3 -m venv .venv
          . .venv/bin/activate


      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker image build, test and push
        run: |
          # local image build and project documentation generation
          make -s docker/fedora
          # local image tests
          make -s docker/fedora-tests
          # local image push on DockerHub
          docker tag ${IMAGE_NAME} ${DOCKER_IMAGE}
          docker push ${DOCKER_IMAGE}

  ubuntu-native:
    if: false
    name: Ubuntu (native)
    runs-on: ubuntu-latest
    env:
      ODOX_PKG: orthodocs_1.2.1_amd64.deb
    steps:
    - name: Project checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches
        # and tags (default 1).
        fetch-depth: '0'

    - name: pre-requisites
      # install Ninja 'cause of the automatic build parallelism turned on with
      # the number of processors found in the hosting system
      run: |
        cat /etc/os-release
        sudo apt update
        sudo apt upgrade -y
        # TODO: replace deps.sh with a python version based on pydot (installed via pip)
        sudo apt install -y apt-utils openscad git graphviz imagemagick make python3-venv wget xvfb
        wget ${{env.ODOX_URL}}/${{env.ODOX_PKG}}
        sudo apt install ./${{env.ODOX_PKG}}

    - name: Documentation build
      working-directory: ${{github.workspace}}
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r pyreqs.txt
        make -s

    - name: Test runs
      working-directory: ${{github.workspace}}
      run: |
        . .venv/bin/activate
        make -s tests/runs

  # Project build and run tests on Ubuntu based Docker image
  # temporary suspended
  ubuntu-docker:
    name: Ubuntu (Docker)
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Project checkout
      # Checks-out repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches
        # and tags (default 1).
        fetch-depth: '0'

    - name: Warming-up
      run: |
        sudo apt update
        sudo apt upgrade -y
        # TODO: replace deps.sh with a python version based on pydot (installed via pip)
        python3 -m venv .venv

    - name: Documentation & tests
      run: |
        . .venv/bin/activate
        make -s docker/ubuntu
        make -s docker/ubuntu-tests

        # Project build and run tests on Fedora based Docker image
  fedora-docker:
    if: false
    name: Fedora (Docker)
    runs-on: ubuntu-latest
    env:
      IMAGE: ggabbiani/ofl:fedora-39
    steps:
    - name: Project checkout
      # Checks-out repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches
        # and tags (default 1).
        fetch-depth: '0'

    - name: Documentation
      run: docker run -v ${{github.workspace}}:/import -it --rm ${{env.IMAGE}}

    - name: Tests
      run: docker run -v ${{github.workspace}}:/import -it --rm ${{env.IMAGE}} tests/runs
